# Generated by Django 2.2 on 2019-12-07 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_loan_status_loans_unit_station_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='customer_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Unit_station_names'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Loan_status'),
        ),
    ]
