# Generated by Django 2.2 on 2019-12-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191207_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='customer_station',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='loan_status',
        ),
        migrations.DeleteModel(
            name='Loan_status',
        ),
        migrations.DeleteModel(
            name='Loans',
        ),
        migrations.DeleteModel(
            name='Unit_station_names',
        ),
    ]
