# Generated by Django 2.2 on 2019-12-07 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_auto_20191207_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Unit_station_names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=255)),
                ('daily_target', models.IntegerField()),
                ('monthly_target', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('loan_amount', models.IntegerField()),
                ('loan_code', models.CharField(max_length=255)),
                ('loan_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('customer_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Unit_station_names')),
                ('loan_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Loan_status')),
            ],
        ),
    ]
