# Generated by Django 2.2 on 2019-12-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_loan_status_loans_unit_station_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='customer_id',
            field=models.CharField(max_length=255),
        ),
    ]
