# Generated by Django 2.2 on 2019-12-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191207_2306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loans',
        ),
    ]
