# Generated by Django 2.2 on 2019-12-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_customers_repayments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repayments',
            old_name='Amount_paid',
            new_name='amount_paid',
        ),
    ]
