# Generated by Django 2.2 on 2019-12-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20191208_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='gender',
            field=models.CharField(choices=[('1', 'Female'), ('2', 'Male')], default=1, max_length=3),
        ),
        migrations.AlterField(
            model_name='customers',
            name='loan_status',
            field=models.CharField(choices=[('1', 'Never borrowed'), ('2', 'Current Loan'), ('3', 'Repaid'), ('4', 'Suspended'), ('5', 'Blacklisted')], default=2, max_length=3),
        ),
    ]
