# Generated by Django 2.2 on 2019-12-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191208_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name_plural': 'Customers'},
        ),
    ]
