# Generated by Django 2.2 on 2019-12-08 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20191208_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repayments',
            options={'verbose_name_plural': 'Repayments'},
        ),
    ]
