# Generated by Django 2.2 on 2019-12-08 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20191209_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayments',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Customers'),
        ),
    ]
