# Generated by Django 2.2 on 2019-12-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20191209_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayments',
            name='loan_code',
            field=models.CharField(max_length=255),
        ),
    ]
