# Generated by Django 2.2 on 2019-12-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20191209_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayments',
            name='loan_code',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
